version: '3.7'

volumes:
  postgres-data:

services:
  postgres:
    container_name: shoulders_db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=shoulders
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=strongpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shoulders
  app:
    container_name: shoulders_app
    build: ..
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://root:strongpassword@postgres:5432/shoulders_db?schema=public
      - JWT_SECRET=secret
    volumes:
      - .:/app
    networks:
      - shoulders

networks:
  shoulders:
    name: shoulders
